### ISSUE TITLE
Store values which are not provided by the SDK to the disk

### ISSUE THREAD

**Issue by Lihis** [Lihis/ets2-job-logger#23]
Values which are not provided by the SDK should be stored in disk when job is started because the information would be lost when for example the application crashes.

**Comment by Subtixx** [comment]
In my opinion the program should also save failed jobs when closing the application and retry when the program is opened again

**Comment by donatocl** [comment]
Also MaxSpeed need to be saved on disk, because when you close the app with per example 1km to end the job, and open again, the job will report a fake maxspeed, just from the last 1km driven.

**Comment by Lihis** [comment]
Can we trust the users that they don't tamper with the data stored on disk?

**Comment by donatocl** [comment]
Unfortunately we can't, it's a big risk. The only way would be that it is encrypted and protedigo in some way.

**Comment by Lihis** [comment]
Never trust the user input :)

What kind of protection level we are talking about? Can we just generate key pair on user's machine for encryption and decryption?

**Comment by donatocl** [comment]
> 
> 
> Never trust the user input :)
> 
> What kind of protection level we are talking about? Can we just generate key pair on user's machine for encryption and decryption?

That sounds as a great idea.

**Comment by Lihis** [comment]
If we can't trust the user not to tamper with the data then can we trust the user not to use the generated keys for malicious purposes, i.e. use them to decrypt the data for editing and then encrypting it back?

I guess if one really wants a secure option then the program would need to run on a closed hardware with the key pair stored in it. But I guess that's out of question due the inconvenience and costs (the hardware would have to account the physical security also).

So the question is how much effort an attacker is willing to put to break the system? Sure the key pair stored on user's machine would prevent user who doesn't know anything about coding from tampering with the data on disk but someone with some experience with coding would easily write a second program just to decrypt/encrypt the data.

Other option would be that if there is no internet connection just store job information on disk and have the user manually input it through the website. But in case of not delivering the job in one go we would need to ask server when the user plays next time that "does the user have an active job in ets2", if yes then return the fuelConsumed, maxSpeed and distance driven. But for server being able to return sane values for these we would need to send those values every X seconds.

**Comment by donatocl** [comment]
If there is no sure way to write the information locally, I think it is better to spend time discovering the best formula to receive the information online.

I believe that if we send the job information every x seconds, that way we will have the variables stored online. If the user loses connection, these variables should be stored in some way and sent when the internet connection is retrieved.

The distance traveled is not lost when restarting or shutting down the PC, or when the program is closed, the only current problem is with the maximum speed and the fuel consumed.

By sending this data every x seconds, on the web side, it can be put that only if the maxspeed variable is greater than the one already stored in the db, then it replaces it, that way the maximum speed will always be stored.

On the fuelconsumed variable is more complicated, the same logic cannot be applied since if the client closes, it starts counting from 0, therefore in that case the variable already stored with the last one sent from the client should be added. The problem here is how to know if you have to add or maintain the largest value, there are 2 different cases that can occur.

**Comment by donatocl** [comment]
Just to clarify one thing, In recent months I have carried out tests using the application, with more than 30 trusted people, who have different situations and connection qualities, some are constantly falling from the internet, others have very stable connections, etc., to the point where I am going , is that a job has never been lost, they always have one way or another internet connection, since the vast majority (if not all) play online on TruckersMP servers.

**Comment by Lihis** [comment]
> I believe that if we send the job information every x seconds, that way we will have the variables stored online. If the user loses connection, these variables should be stored in some way and sent when the internet connection is retrieved.

These can be kept in memory just like the jobs.

> On the fuelconsumed variable is more complicated, the same logic cannot be applied since if the client closes, it starts counting from 0, therefore in that case the variable already stored with the last one sent from the client should be added. The problem here is how to know if you have to add or maintain the largest value, there are 2 different cases that can occur.

Instead of sending the calculated amount could it be calculated with the same logic on server side?

**Comment by donatocl** [comment]
> These can be kept in memory just like the jobs.
Yes, that is perfect.

> Instead of sending the calculated amount could it be calculated with the same logic on server side?
Yes, this will be a good solution, but how It will work? You mean that the client will be sent the amount used in the last x seconds so server side will always sum the incoming fuel consumed?

**Comment by Lihis** [comment]
> Yes, this will be a good solution, but how It will work? You mean that the client will be sent the amount used in the last x seconds so server side will always sum the incoming fuel consumed?

If you look the [code](https://github.com/Lihis/ets2-job-logger/blob/27ca314cccd0510123e410583a5d5a82ba55aae3/gui/MainWindow.cpp#L271) the same would be then done on the server. But is it just me or does that look flawed? Because it also needs to account for refill.

**Comment by Lihis** [comment]
Closing this in favor of #44.
