### ISSUE TITLE
General code update

### ISSUE THREAD

**Issue by ResTedRU** [Lihis/ets2-job-logger#54]
I have been trying to build a project lately, but I keep running into problems that are related to outdated tools and libraries. Is it possible to make a global update for code and tools in order to use current tools, for example VS2022. (_talking about the assembly on Windows_)

Also, after the last update job_logger, new data have been added that can be obtained from game, and some old data have been changed.
For example:

1. update was added: when you use F7 when using an external contract, then the cargo in the game disappears, but the program does not see it (there must be an event - refusal of cargo: change of status from `1 = OnJob` to `2 = Cancelled` )

2. some data we receive does not contain valid data, but for some reason such data is replaced by _0. 
This is probably due to the fact that `.` is replaced by `_` . (https://prnt.sc/26c6n2i)

I hope this will be possible.
I would like to support you in this in different ways ))

**Comment by Lihis** [comment]
About the libraries, one could check if the `conanfile.txt` has a way to "install always the latest version", that would be much better than manually bumping the versions. Otherwise the libraries should now be up-to-date (except forgot to bump up the cURL version) but the build is broken, see #53.

What comes to Visual Studio, I haven't had access to a Windows for a couple years. Someone was trying to use VS2019 but there was some build (see #9). So any PR's allowing to use newer VS is welcome (like for the #53).

> when you use F7 when using an external contract, then the cargo in the game disappears, but the program does not see it

With `F7` you mean the "tow to service"? The SDK only has [delivered](https://github.com/Lihis/scs-sdk/blob/98d082f9a4dd3c342e4f73be1bcea239d5c70bbb/include/scs/common/scssdk_telemetry_common_gameplay_events.h#L19) and [delivered](https://github.com/Lihis/scs-sdk/blob/98d082f9a4dd3c342e4f73be1bcea239d5c70bbb/include/scs/common/scssdk_telemetry_common_gameplay_events.h#L33) so need to spin up and the game and add some logging to debug.

> some data we receive does not contain valid data, but for some reason such data is replaced by _0

Seems weird. Some unit tests should be written at some point.

**Comment by Lihis** [comment]
Closing as code seems to be up-to-date because builds for three Linux distros (Arch Linux and Fedora added in 3722929b3c7b2d2a859510b45fda0f26c78d3163) are passing. Also some first unit tests has been merged in #60 which seem to be passing.
