### ISSUE TITLE
SDK and Game Version

### ISSUE THREAD

**Issue by donatocl** [Lihis/ets2-job-logger#8]
I have compiled the plugin with the SDK 1.10, that is compatible for game 1.35, now the game is on 1.36, need to compile with SDK 1.11?

I have this doubt because when the program is open I can't see any information displayed as you can see in the image.
![2019-12-17 16_24_10-New Issue · Lihis_ets2-job-logger](https://user-images.githubusercontent.com/58643272/71027281-af601580-20e9-11ea-9f9e-621969ca6be9.png)

I have the game open and I took a job neither sends information to the API.

**Comment by Lihis** [comment]
Tested here on Linux with game version `1.36.2.13` and it works with SDK version `1.10`.

Could you enable [console](https://forum.scssoft.com/viewtopic.php?t=61852) and see does it throw any sane error in the log; start the game after you enabled console, on profile selection screen bring up the console and there should be line saying `loading 'ets2-job-logger'` and hopefully some helpful error after that.

------

Seems that I have forgotten to tag v1.10 release of SDK in [scs-sdk](https://github.com/Lihis/scs-sdk/) so tagged it now, will need to update our `scs-sdk` point to that.

There also seems to be sort of encoding issue, income should be `€`, not that what is in your screenshot.

**Comment by donatocl** [comment]
Here is the console log 
![2019-12-17 18_42_33-Euro Truck Simulator 2](https://user-images.githubusercontent.com/58643272/71036763-0fac8280-20fd-11ea-8301-51afe9462f35.png)

**Comment by donatocl** [comment]
Hey Lihis, also just to let you know, I sent you an email to lihis@lihis.net about a project, thank you!

**Comment by Lihis** [comment]
I had some issues when I was testing it in Wine some 8 months ago but I don't remember did I get that same error message. The issue was fixed by linking some additional [libraries](https://github.com/Lihis/ets2-job-logger/blob/master/plugin/CMakeLists.txt#L30). But I suspect that the partly respective fix wont help:
```
if (MSVC)
    set(WIN32_LIBS
        wsock32.lib
        ws2_32.lib
        )
endif()
```

Anyway I would suggest to try to find out if some library is missing by using `Dependency Walker` or according [this](https://stackoverflow.com/a/7378982/3101793) it's rewrite or the tool of your choice to find out the dependencies. Visual Studio also ships with `dumpbin.exe` (found deep under `Program Files\Microsoft Visual Studio`). Then identify are those dependent libraries present on your computer. If a library is not found we probably should link it to the plugin statically.

**Comment by Lihis** [comment]
Surprisingly ETS2 started in Virtualbox so I was able to run it via `Dependency Walker` with `Profiling` and the error was pretty clear in there:

```
GetProcAddress(0x00007FFFEB430000 [ETS2-JOB-LOGGER.DLL], "scs_telemetry_init") called from "EUROTRUCKS2.EXE" at address 0x00007FF6F2210751 and returned NULL. Error: The specified procedure could not be found (127).
GetProcAddress(0x00007FFFEB430000 [ETS2-JOB-LOGGER.DLL], "scs_telemetry_shutdown") called from "EUROTRUCKS2.EXE" at address 0x00007FF6F2210766 and returned NULL. Error: The specified procedure could not be found (127).
```

Should be fixed now in `master`.
